### 连localhost sql server

In [4]:
import pymssql

In [ ]:
conn=pymssql.connect(server='192.168.1.118',user='sa',password='123456',database='ZL_STG')

In [ ]:
import pandas as pd
sql='SELECT * FROM [ZL_STG].[dbo].[ZL_STG_Amazon_Payments_2018_quan]'
df0=pd.read_sql(sql,conn)
df=pd.DataFrame(df0)

### 连远程sql server

In [7]:
import pymssql

In [12]:
conn=pymssql.connect(server='192.168.1.156',user='sa',password='Sa123456',database='ZL_Payments_Data')
sql='SELECT Top 1000000 * FROM [ZL_Payments_Data].[dbo].[ZL_STG_Amazon_Payments_2018_to_2021_quan]'
df0=pd.read_sql(sql,conn)
df=pd.DataFrame(df0)

In [13]:
df

               website currency behavior            date_time  ... other_transaction_fees other   total diff_amount
0        201906月__us3站      USD     商品销售  2019-06-19 19:49:40  ...                      0     0   12.58           0
1        201906月__us3站      USD     商品销售  2019-06-19 19:52:01  ...                      0     0   14.28           0
2        201906月__us3站      USD     商品销售  2019-06-19 19:52:18  ...                      0     0   17.39           0
3        201906月__us3站      USD     商品销售  2019-06-19 19:52:28  ...                      0     0   21.82           0
4        201906月__us3站      USD     商品销售  2019-06-19 19:58:10  ...                      0     0    9.68           0
...                ...      ...      ...                  ...  ...                    ...   ...     ...         ...
999995  202112月__us07站      USD     销售退款  2021-12-07 20:00:59  ...                      0     0  -18.29           0
999996  202112月__us07站      USD     商品销售  2021-12-07 20:02:07  ...                      0     0   12.04           0
999997  202112月__us07站      USD     商品销售  2021-12-07 20:02:11  ...                      0     0   11.01           0
999998  202112月__us07站      USD     商品销售  2021-12-07 20:18:44  ...                      0     0   22.61           0
999999  202112月__us07站      USD     销售退款  2021-12-07 20:21:30  ...                      0     0  -14.77           0

[1000000 rows x 36 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 36 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   website                      1000000 non-null  object
 1   currency                     1000000 non-null  object
 2   behavior                     1000000 non-null  object
 3   date_time                    1000000 non-null  object
 4   settlement_id                1000000 non-null  object
 5   type                         965539 non-null   object
 6   order_id                     991721 non-null   object
 7   sku                          949754 non-null   object
 8   description                  999977 non-null   object
 9   quantity                     989562 non-null   float64
 10  marketplace                  986246 non-null   object
 11  account_type                 465728 non-null   object
 12  fulfillment                  950579 non-null   object
 13  order_city                   938296 non-null   object
 14  order_state                  832221 non-null   object
 15  order_postal                 914488 non-null   object
 16  tax_collection_model         720041 non-null   object
 17  product_sales                1000000 non-null  object
 18  product_sales_tax            999946 non-null   object
 19  shipping_credits             1000000 non-null  object
 20  shipping_credits_tax         999946 non-null   object
 21  gift_wrap_credits            999998 non-null   object
 22  gift_wrap_credits_tax        999946 non-null   object
 23  promotional_rebates          1000000 non-null  object
 24  promotional_rebates_tax      999946 non-null   object
 25  sales_tax_collected          624055 non-null   object
 26  low_value_goods              621686 non-null   object
 27  marketplace_facilitator_tax  621692 non-null   object
 28  marketplace_withheld_tax     997675 non-null   object
 29  selling_fees                 1000000 non-null  object
 30  fba_fees                     1000000 non-null  object
 31  points_fees                  621686 non-null   object
 32  other_transaction_fees       1000000 non-null  object
 33  other                        999994 non-null   object
 34  total                        999994 non-null   object
 35  diff_amount                  1000000 non-null  object
dtypes: float64(1), object(35)
memory usage: 274.7+ MB

In [24]:
df['product_sales']=df['product_sales'].astype('float')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 36 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   website                      1000000 non-null  object
 1   currency                     1000000 non-null  object
 2   behavior                     1000000 non-null  object
 3   date_time                    1000000 non-null  object
 4   settlement_id                1000000 non-null  object
 5   type                         965539 non-null   object
 6   order_id                     991721 non-null   object
 7   sku                          949754 non-null   object
 8   description                  999977 non-null   object
 9   quantity                     989562 non-null   float64
 10  marketplace                  986246 non-null   object
 11  account_type                 465728 non-null   object
 12  fulfillment                  950579 non-null   object
 13  order_city                   938296 non-null   object
 14  order_state                  832221 non-null   object
 15  order_postal                 914488 non-null   object
 16  tax_collection_model         720041 non-null   object
 17  product_sales                1000000 non-null  float64
 18  product_sales_tax            999946 non-null   object
 19  shipping_credits             1000000 non-null  object
 20  shipping_credits_tax         999946 non-null   object
 21  gift_wrap_credits            999998 non-null   object
 22  gift_wrap_credits_tax        999946 non-null   object
 23  promotional_rebates          1000000 non-null  object
 24  promotional_rebates_tax      999946 non-null   object
 25  sales_tax_collected          624055 non-null   object
 26  low_value_goods              621686 non-null   object
 27  marketplace_facilitator_tax  621692 non-null   object
 28  marketplace_withheld_tax     997675 non-null   object
 29  selling_fees                 1000000 non-null  object
 30  fba_fees                     1000000 non-null  object
 31  points_fees                  621686 non-null   object
 32  other_transaction_fees       1000000 non-null  object
 33  other                        999994 non-null   object
 34  total                        999994 non-null   object
 35  diff_amount                  1000000 non-null  object
dtypes: float64(2), object(34)
memory usage: 274.7+ MB

In [26]:
df_group=df.groupby(by='marketplace')

In [29]:
df_group.sum()[['product_sales']]

                                           product_sales
marketplace
                                                    0.00
0                                                   0.00
Amazon.ca                                           0.00
Amazon.co.jp                                        0.00
Amazon.co.uk                                  1314780.47
Amazon.com                                    8459631.19
Amazon.com.mx                                       0.00
Amazon.de                                      570951.90
Amazon.es                                           0.00
Amazon.fr                                      179881.30
Amazon.it                                           0.00
amazon.ca                                      107292.02
amazon.co.uk                                  1199988.46
amazon.com                                    5926771.12
amazon.com.mx                                  214818.98
amazon.com.tr                                     484.96
amazon.de                                     1503826.97
amazon.es                                      244526.48
amazon.fr                                      743637.15
amazon.it                                      518517.98
amazon.jp                                    41018762.00
amazon.nl                                        1766.03
amazon.pl                                        4779.04
amazon.se                                       13241.47
jp-shipment-injection.stores.amazon.co.jp           0.00
si-prod-fr-marketplace.stores.amazon.fr             0.00
si-prod-marketplace-de.stores.amazon.de             0.00
sim1.stores.amazon.com                              0.00
siprod.stores.amazon.es                             0.00
siprod.stores.amazon.it                             0.00
siprodukmarketplace.stores.amazon.co.uk             0.00